# Generated by Django 6.1.1 on 2026-09-14 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=80, verbose_name='название (ru)')),
                ('name_en', models.CharField(max_length=80, verbose_name='название (en)')),
                ('name_tg', models.CharField(max_length=80, verbose_name='название (tg)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='порядок сортировки')),
            ],
            options={
                'verbose_name': 'категория места',
                'verbose_name_plural': 'категории мест',
                'ordering': ['position', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=120, verbose_name='название (ru)')),
                ('name_en', models.CharField(max_length=120, verbose_name='название (en)')),
                ('name_tg', models.CharField(max_length=120, verbose_name='название (tg)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'регион',
                'verbose_name_plural': 'регионы',
                'ordering': ['position', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название (ru)')),
                ('name_en', models.CharField(max_length=200, verbose_name='название (en)')),
                ('name_tg', models.CharField(max_length=200, verbose_name='название (tg)')),
                ('description_ru', models.TextField(blank=True, verbose_name='описание (ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='описание (en)')),
                ('description_tg', models.TextField(blank=True, verbose_name='описание (tg)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('opening_hours', models.TextField(blank=True, verbose_name='часы работы')),
                ('entrance_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='входная цена, сомони')),
                ('access_difficulty', models.CharField(choices=[('easy_walk', 'лёгкая пешая прогулка'), ('need_offroad', 'нужен внедорожник'), ('mountain_hike', 'горный поход'), ('other', 'другое')], default='easy_walk', max_length=20, verbose_name='сложность доступа')),
                ('recommended_seasons', models.JSONField(blank=True, default=list, verbose_name='рекомендуемое время года')),
                ('moderation_status', models.CharField(choices=[('pending', 'на проверке'), ('published', 'опубликовано'), ('rejected', 'отклонено')], default='pending', max_length=20, verbose_name='статус модерации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_places', to=settings.AUTH_USER_MODEL, verbose_name='добавил (волонтёр)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.placecategory', verbose_name='категория')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/%Y/%m/', verbose_name='файл')),
                ('caption_ru', models.CharField(blank=True, max_length=300, verbose_name='подпись (ru)')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='подпись (en)')),
                ('caption_tg', models.CharField(blank=True, max_length=300, verbose_name='подпись (tg)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place', verbose_name='место')),
            ],
            options={
                'verbose_name': 'фотография места',
                'verbose_name_plural': 'фотографии мест',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
