# Generated by Django 6.1.1 on 2026-09-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-is_promoted', 'name_ru'], 'verbose_name': 'место', 'verbose_name_plural': 'места'},
        ),
        migrations.AddField(
            model_name='place',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='продвижение в топе (Этап 7)'),
        ),
    ]
