# Generated by Django 6.1.1 on 2026-09-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (en)')),
                ('name_tg', models.CharField(max_length=255, verbose_name='Название (tg)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (en)')),
                ('description_tg', models.TextField(blank=True, verbose_name='Описание (tg)')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Количество дней')),
                ('moderation_status', models.CharField(choices=[('pending', 'На проверке'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Продвижение в топе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='places.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ['-is_promoted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='День')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в дне')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время (минуты)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='places.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['day', 'order'],
            },
        ),
    ]
