# Generated by Django 6.1.1 on 2026-09-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='код')),
                ('name_ru', models.CharField(max_length=80, verbose_name='название (ru)')),
                ('name_en', models.CharField(max_length=80, verbose_name='название (en)')),
                ('name_tg', models.CharField(max_length=80, verbose_name='название (tg)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='порядок сортировки')),
            ],
            options={
                'verbose_name': 'категория объекта бронирования',
                'verbose_name_plural': 'категории объектов бронирования',
                'ordering': ['position', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='BookingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=200, verbose_name='название (ru)')),
                ('name_en', models.CharField(max_length=200, verbose_name='название (en)')),
                ('name_tg', models.CharField(max_length=200, verbose_name='название (tg)')),
                ('description_ru', models.TextField(blank=True, verbose_name='описание (ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='описание (en)')),
                ('description_tg', models.TextField(blank=True, verbose_name='описание (tg)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='сайт')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='продвижение в топе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_objects', to='booking.bookingcategory', verbose_name='категория')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_booking_objects', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('places', models.ManyToManyField(blank=True, related_name='booking_objects', to='places.place', verbose_name='связанные места')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_objects', to='places.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'объект бронирования',
                'verbose_name_plural': 'объекты бронирования',
                'ordering': ['-is_promoted', 'name_ru'],
            },
        ),
    ]
