# Generated by Django 6.1.1 on 2026-09-14 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_name', models.CharField(max_length=200, verbose_name='имя туриста')),
                ('tourist_contact', models.CharField(max_length=200, verbose_name='контакт туриста (телефон/email)')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='дата заезда')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='дата выезда')),
                ('notes', models.TextField(blank=True, verbose_name='комментарий')),
                ('pay_on_site', models.BooleanField(default=False, verbose_name='оплата на месте')),
                ('status', models.CharField(choices=[('new', 'новая'), ('confirmed', 'подтверждена'), ('rejected', 'отклонена'), ('cancelled', 'отменена туристом')], default='new', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='booking.bookingobject', verbose_name='объект бронирования')),
                ('tourist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to=settings.AUTH_USER_MODEL, verbose_name='турист')),
            ],
            options={
                'verbose_name': 'заявка на бронирование',
                'verbose_name_plural': 'заявки на бронирование',
                'ordering': ['-created_at'],
            },
        ),
    ]
